//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:19:14 PM MSK 
//


package ru.gov.zakupki._223fz.contract._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о расторжении договора
 * 
 * <p>Java class for contractCancellationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractCancellationDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/contract/1}contractCompletingDataType">
 *       &lt;sequence>
 *         &lt;element name="completionInfo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="completionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="baseRejectionDocName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="baseRejectionDocNum">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="baseRejectionDocDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractCancellationDataType", propOrder = {
    "completionInfo",
    "completionDate",
    "baseRejectionDocName",
    "baseRejectionDocNum",
    "baseRejectionDocDate"
})
public class ContractCancellationDataType
    extends ContractCompletingDataType
{

    @XmlElement(required = true)
    protected String completionInfo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar completionDate;
    @XmlElement(required = true)
    protected String baseRejectionDocName;
    @XmlElement(required = true)
    protected String baseRejectionDocNum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar baseRejectionDocDate;

    /**
     * Gets the value of the completionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionInfo() {
        return completionInfo;
    }

    /**
     * Sets the value of the completionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionInfo(String value) {
        this.completionInfo = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletionDate(XMLGregorianCalendar value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the baseRejectionDocName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRejectionDocName() {
        return baseRejectionDocName;
    }

    /**
     * Sets the value of the baseRejectionDocName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRejectionDocName(String value) {
        this.baseRejectionDocName = value;
    }

    /**
     * Gets the value of the baseRejectionDocNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseRejectionDocNum() {
        return baseRejectionDocNum;
    }

    /**
     * Sets the value of the baseRejectionDocNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseRejectionDocNum(String value) {
        this.baseRejectionDocNum = value;
    }

    /**
     * Gets the value of the baseRejectionDocDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBaseRejectionDocDate() {
        return baseRejectionDocDate;
    }

    /**
     * Sets the value of the baseRejectionDocDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBaseRejectionDocDate(XMLGregorianCalendar value) {
        this.baseRejectionDocDate = value;
    }

}
