//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:17:00 PM MSK 
//


package ru.gov.zakupki._223fz.types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolTemplateFieldPlaceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="protocolTemplateFieldPlaceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MAIN"/>
 *     &lt;enumeration value="APP_INFO"/>
 *     &lt;enumeration value="COMMISSION_ACCESS"/>
 *     &lt;enumeration value="COMMISSION_RESULT"/>
 *     &lt;enumeration value="DOCS"/>
 *     &lt;enumeration value="EXTEND"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "protocolTemplateFieldPlaceType")
@XmlEnum
public enum ProtocolTemplateFieldPlaceType {


    /**
     * Общая информация
     * 
     */
    MAIN,

    /**
     * Сведения о заявке
     * 
     */
    APP_INFO,

    /**
     * Решения комиссии. Допуск
     * 
     */
    COMMISSION_ACCESS,

    /**
     * Решения комиссии. Результат
     * 
     */
    COMMISSION_RESULT,

    /**
     * Документация
     * 
     */
    DOCS,

    /**
     * Дополнительные данные
     * 
     */
    EXTEND;

    public String value() {
        return name();
    }

    public static ProtocolTemplateFieldPlaceType fromValue(String v) {
        return valueOf(v);
    }

}
