//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:17:31 PM MSK 
//


package ru.gov.zakupki._223fz.complaint._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Решение по жалобе
 * 
 * <p>Java class for complaintDecisionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="complaintDecisionDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="guid" type="{http://zakupki.gov.ru/223fz/types/1}guidType"/>
 *         &lt;element name="registrationNumber" type="{http://zakupki.gov.ru/223fz/complaint/1}complaintNumber" minOccurs="0"/>
 *         &lt;element name="publishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="version" type="{http://zakupki.gov.ru/223fz/types/1}versionType" minOccurs="0"/>
 *         &lt;element name="status" type="{http://zakupki.gov.ru/223fz/complaint/1}complaintDecisionStatusType"/>
 *         &lt;element name="complaintDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="modificationDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="complaintDecisionSolution" type="{http://zakupki.gov.ru/223fz/complaint/1}complaintDecisionSolutionType"/>
 *         &lt;element name="complaintDecisionViolation" type="{http://zakupki.gov.ru/223fz/complaint/1}complaintDecisionViolationType"/>
 *         &lt;element name="prescription" type="{http://zakupki.gov.ru/223fz/complaint/1}prescriptionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complaintDecisionDataType", propOrder = {
    "guid",
    "registrationNumber",
    "publishDate",
    "version",
    "status",
    "complaintDate",
    "modificationDescription",
    "complaintDecisionSolution",
    "complaintDecisionViolation",
    "prescription"
})
public class ComplaintDecisionDataType {

    @XmlElement(required = true)
    protected String guid;
    protected String registrationNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publishDate;
    protected Long version;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ComplaintDecisionStatusType status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar complaintDate;
    protected String modificationDescription;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ComplaintDecisionSolutionType complaintDecisionSolution;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ComplaintDecisionViolationType complaintDecisionViolation;
    @XmlElement(required = true)
    protected PrescriptionType prescription;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublishDate(XMLGregorianCalendar value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ComplaintDecisionStatusType }
     *     
     */
    public ComplaintDecisionStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplaintDecisionStatusType }
     *     
     */
    public void setStatus(ComplaintDecisionStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the complaintDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getComplaintDate() {
        return complaintDate;
    }

    /**
     * Sets the value of the complaintDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setComplaintDate(XMLGregorianCalendar value) {
        this.complaintDate = value;
    }

    /**
     * Gets the value of the modificationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationDescription() {
        return modificationDescription;
    }

    /**
     * Sets the value of the modificationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationDescription(String value) {
        this.modificationDescription = value;
    }

    /**
     * Gets the value of the complaintDecisionSolution property.
     * 
     * @return
     *     possible object is
     *     {@link ComplaintDecisionSolutionType }
     *     
     */
    public ComplaintDecisionSolutionType getComplaintDecisionSolution() {
        return complaintDecisionSolution;
    }

    /**
     * Sets the value of the complaintDecisionSolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplaintDecisionSolutionType }
     *     
     */
    public void setComplaintDecisionSolution(ComplaintDecisionSolutionType value) {
        this.complaintDecisionSolution = value;
    }

    /**
     * Gets the value of the complaintDecisionViolation property.
     * 
     * @return
     *     possible object is
     *     {@link ComplaintDecisionViolationType }
     *     
     */
    public ComplaintDecisionViolationType getComplaintDecisionViolation() {
        return complaintDecisionViolation;
    }

    /**
     * Sets the value of the complaintDecisionViolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplaintDecisionViolationType }
     *     
     */
    public void setComplaintDecisionViolation(ComplaintDecisionViolationType value) {
        this.complaintDecisionViolation = value;
    }

    /**
     * Gets the value of the prescription property.
     * 
     * @return
     *     possible object is
     *     {@link PrescriptionType }
     *     
     */
    public PrescriptionType getPrescription() {
        return prescription;
    }

    /**
     * Sets the value of the prescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescriptionType }
     *     
     */
    public void setPrescription(PrescriptionType value) {
        this.prescription = value;
    }

}
