//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 04:59:41 PM MSK 
//


package ru.gov.zakupki._223fz.webrequest._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki._223fz.webrequest._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki._223fz.webrequest._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PublishedDataResponse }
     * 
     */
    public PublishedDataResponse createPublishedDataResponse() {
        return new PublishedDataResponse();
    }

    /**
     * Create an instance of {@link PublishedDataRequest }
     * 
     */
    public PublishedDataRequest createPublishedDataRequest() {
        return new PublishedDataRequest();
    }

    /**
     * Create an instance of {@link PlanVersionsDataResponse }
     * 
     */
    public PlanVersionsDataResponse createPlanVersionsDataResponse() {
        return new PlanVersionsDataResponse();
    }

    /**
     * Create an instance of {@link PlanVersionsDataType }
     * 
     */
    public PlanVersionsDataType createPlanVersionsDataType() {
        return new PlanVersionsDataType();
    }

    /**
     * Create an instance of {@link PublishedDataType }
     * 
     */
    public PublishedDataType createPublishedDataType() {
        return new PublishedDataType();
    }

    /**
     * Create an instance of {@link PublishedDataRequest.Body }
     * 
     */
    public PublishedDataRequest.Body createPublishedDataRequestBody() {
        return new PublishedDataRequest.Body();
    }

    /**
     * Create an instance of {@link PublishedDataResponse.Body }
     * 
     */
    public PublishedDataResponse.Body createPublishedDataResponseBody() {
        return new PublishedDataResponse.Body();
    }

    /**
     * Create an instance of {@link PlanVersionsDataResponse.Body }
     * 
     */
    public PlanVersionsDataResponse.Body createPlanVersionsDataResponseBody() {
        return new PlanVersionsDataResponse.Body();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link PlanVersionType }
     * 
     */
    public PlanVersionType createPlanVersionType() {
        return new PlanVersionType();
    }

    /**
     * Create an instance of {@link PlanVersionsDataType.Versions }
     * 
     */
    public PlanVersionsDataType.Versions createPlanVersionsDataTypeVersions() {
        return new PlanVersionsDataType.Versions();
    }

    /**
     * Create an instance of {@link PublishedDataType.Items }
     * 
     */
    public PublishedDataType.Items createPublishedDataTypeItems() {
        return new PublishedDataType.Items();
    }

    /**
     * Create an instance of {@link PublishedDataRequest.Body.GuidList }
     * 
     */
    public PublishedDataRequest.Body.GuidList createPublishedDataRequestBodyGuidList() {
        return new PublishedDataRequest.Body.GuidList();
    }

}
