//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 04:40:02 PM MSK 
//


package ru.gov.zakupki._223fz.purchase._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki._223fz.purchase._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki._223fz.purchase._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PurchaseContractAccount }
     * 
     */
    public PurchaseContractAccount createPurchaseContractAccount() {
        return new PurchaseContractAccount();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocation }
     * 
     */
    public ProtocolLotAllocation createProtocolLotAllocation() {
        return new ProtocolLotAllocation();
    }

    /**
     * Create an instance of {@link PurchaseProtocol }
     * 
     */
    public PurchaseProtocol createPurchaseProtocol() {
        return new PurchaseProtocol();
    }

    /**
     * Create an instance of {@link ChangeRequirements }
     * 
     */
    public ChangeRequirements createChangeRequirements() {
        return new ChangeRequirements();
    }

    /**
     * Create an instance of {@link PurchaseRejection }
     * 
     */
    public PurchaseRejection createPurchaseRejection() {
        return new PurchaseRejection();
    }

    /**
     * Create an instance of {@link PurchaseProtocolOSZ }
     * 
     */
    public PurchaseProtocolOSZ createPurchaseProtocolOSZ() {
        return new PurchaseProtocolOSZ();
    }

    /**
     * Create an instance of {@link Explanation }
     * 
     */
    public Explanation createExplanation() {
        return new Explanation();
    }

    /**
     * Create an instance of {@link PurchaseProtocolVK }
     * 
     */
    public PurchaseProtocolVK createPurchaseProtocolVK() {
        return new PurchaseProtocolVK();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAOA }
     * 
     */
    public PurchaseProtocolPAOA createPurchaseProtocolPAOA() {
        return new PurchaseProtocolPAOA();
    }

    /**
     * Create an instance of {@link PurchaseContract }
     * 
     */
    public PurchaseContract createPurchaseContract() {
        return new PurchaseContract();
    }

    /**
     * Create an instance of {@link PurchaseNoticeEP }
     * 
     */
    public PurchaseNoticeEP createPurchaseNoticeEP() {
        return new PurchaseNoticeEP();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZK }
     * 
     */
    public PurchaseProtocolZK createPurchaseProtocolZK() {
        return new PurchaseProtocolZK();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAE }
     * 
     */
    public PurchaseProtocolRZAE createPurchaseProtocolRZAE() {
        return new PurchaseProtocolRZAE();
    }

    /**
     * Create an instance of {@link ProtocolCancellation }
     * 
     */
    public ProtocolCancellation createProtocolCancellation() {
        return new ProtocolCancellation();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZK }
     * 
     */
    public PurchaseNoticeZK createPurchaseNoticeZK() {
        return new PurchaseNoticeZK();
    }

    /**
     * Create an instance of {@link PurchaseNotice }
     * 
     */
    public PurchaseNotice createPurchaseNotice() {
        return new PurchaseNotice();
    }

    /**
     * Create an instance of {@link ExplanationRequest }
     * 
     */
    public ExplanationRequest createExplanationRequest() {
        return new ExplanationRequest();
    }

    /**
     * Create an instance of {@link VolumeInnovPurchase }
     * 
     */
    public VolumeInnovPurchase createVolumeInnovPurchase() {
        return new VolumeInnovPurchase();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE }
     * 
     */
    public PurchaseProtocolPAAE createPurchaseProtocolPAAE() {
        return new PurchaseProtocolPAAE();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOA }
     * 
     */
    public PurchaseProtocolRZOA createPurchaseProtocolRZOA() {
        return new PurchaseProtocolRZOA();
    }

    /**
     * Create an instance of {@link VolumeMonitoring }
     * 
     */
    public VolumeMonitoring createVolumeMonitoring() {
        return new VolumeMonitoring();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AE }
     * 
     */
    public PurchaseProtocolRZ1AE createPurchaseProtocolRZ1AE() {
        return new PurchaseProtocolRZ1AE();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOK }
     * 
     */
    public PurchaseNoticeOK createPurchaseNoticeOK() {
        return new PurchaseNoticeOK();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ2AE }
     * 
     */
    public PurchaseProtocolRZ2AE createPurchaseProtocolRZ2AE() {
        return new PurchaseProtocolRZ2AE();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE94FZ }
     * 
     */
    public PurchaseNoticeAE94FZ createPurchaseNoticeAE94FZ() {
        return new PurchaseNoticeAE94FZ();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKESMBO }
     * 
     */
    public PurchaseNoticeZKESMBO createPurchaseNoticeZKESMBO() {
        return new PurchaseNoticeZKESMBO();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE }
     * 
     */
    public PurchaseNoticeAE createPurchaseNoticeAE() {
        return new PurchaseNoticeAE();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOK }
     * 
     */
    public PurchaseProtocolRZOK createPurchaseProtocolRZOK() {
        return new PurchaseProtocolRZOK();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE94FZ }
     * 
     */
    public PurchaseProtocolPAAE94FZ createPurchaseProtocolPAAE94FZ() {
        return new PurchaseProtocolPAAE94FZ();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZPESMBO }
     * 
     */
    public PurchaseNoticeZPESMBO createPurchaseNoticeZPESMBO() {
        return new PurchaseNoticeZPESMBO();
    }

    /**
     * Create an instance of {@link ListInnov }
     * 
     */
    public ListInnov createListInnov() {
        return new ListInnov();
    }

    /**
     * Create an instance of {@link VolumePurchase }
     * 
     */
    public VolumePurchase createVolumePurchase() {
        return new VolumePurchase();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellation }
     * 
     */
    public PurchaseLotCancellation createPurchaseLotCancellation() {
        return new PurchaseLotCancellation();
    }

    /**
     * Create an instance of {@link ListGWS }
     * 
     */
    public ListGWS createListGWS() {
        return new ListGWS();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOA }
     * 
     */
    public PurchaseNoticeOA createPurchaseNoticeOA() {
        return new PurchaseNoticeOA();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAEP }
     * 
     */
    public PurchaseProtocolPAEP createPurchaseProtocolPAEP() {
        return new PurchaseProtocolPAEP();
    }

    /**
     * Create an instance of {@link PurchaseNoticeDataType }
     * 
     */
    public PurchaseNoticeDataType createPurchaseNoticeDataType() {
        return new PurchaseNoticeDataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeDataType.TemplateStructure }
     * 
     */
    public PurchaseNoticeDataType.TemplateStructure createPurchaseNoticeDataTypeTemplateStructure() {
        return new PurchaseNoticeDataType.TemplateStructure();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocationData }
     * 
     */
    public ProtocolLotAllocationData createProtocolLotAllocationData() {
        return new ProtocolLotAllocationData();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocationData.AllocatedLots }
     * 
     */
    public ProtocolLotAllocationData.AllocatedLots createProtocolLotAllocationDataAllocatedLots() {
        return new ProtocolLotAllocationData.AllocatedLots();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellationData }
     * 
     */
    public PurchaseLotCancellationData createPurchaseLotCancellationData() {
        return new PurchaseLotCancellationData();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellationData.CancelledLots }
     * 
     */
    public PurchaseLotCancellationData.CancelledLots createPurchaseLotCancellationDataCancelledLots() {
        return new PurchaseLotCancellationData.CancelledLots();
    }

    /**
     * Create an instance of {@link PurchaseProtocolDataType }
     * 
     */
    public PurchaseProtocolDataType createPurchaseProtocolDataType() {
        return new PurchaseProtocolDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolDataType.TemplateStructure }
     * 
     */
    public PurchaseProtocolDataType.TemplateStructure createPurchaseProtocolDataTypeTemplateStructure() {
        return new PurchaseProtocolDataType.TemplateStructure();
    }

    /**
     * Create an instance of {@link ProtocolCancellationDataType }
     * 
     */
    public ProtocolCancellationDataType createProtocolCancellationDataType() {
        return new ProtocolCancellationDataType();
    }

    /**
     * Create an instance of {@link PurchaseContractAccount.Body }
     * 
     */
    public PurchaseContractAccount.Body createPurchaseContractAccountBody() {
        return new PurchaseContractAccount.Body();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocation.Body }
     * 
     */
    public ProtocolLotAllocation.Body createProtocolLotAllocationBody() {
        return new ProtocolLotAllocation.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocol.Body }
     * 
     */
    public PurchaseProtocol.Body createPurchaseProtocolBody() {
        return new PurchaseProtocol.Body();
    }

    /**
     * Create an instance of {@link ChangeRequirements.Body }
     * 
     */
    public ChangeRequirements.Body createChangeRequirementsBody() {
        return new ChangeRequirements.Body();
    }

    /**
     * Create an instance of {@link PurchaseRejection.Body }
     * 
     */
    public PurchaseRejection.Body createPurchaseRejectionBody() {
        return new PurchaseRejection.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolOSZ.Body }
     * 
     */
    public PurchaseProtocolOSZ.Body createPurchaseProtocolOSZBody() {
        return new PurchaseProtocolOSZ.Body();
    }

    /**
     * Create an instance of {@link Explanation.Body }
     * 
     */
    public Explanation.Body createExplanationBody() {
        return new Explanation.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolVK.Body }
     * 
     */
    public PurchaseProtocolVK.Body createPurchaseProtocolVKBody() {
        return new PurchaseProtocolVK.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAOA.Body }
     * 
     */
    public PurchaseProtocolPAOA.Body createPurchaseProtocolPAOABody() {
        return new PurchaseProtocolPAOA.Body();
    }

    /**
     * Create an instance of {@link PurchaseContract.Body }
     * 
     */
    public PurchaseContract.Body createPurchaseContractBody() {
        return new PurchaseContract.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeEP.Body }
     * 
     */
    public PurchaseNoticeEP.Body createPurchaseNoticeEPBody() {
        return new PurchaseNoticeEP.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZK.Body }
     * 
     */
    public PurchaseProtocolZK.Body createPurchaseProtocolZKBody() {
        return new PurchaseProtocolZK.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAE.Body }
     * 
     */
    public PurchaseProtocolRZAE.Body createPurchaseProtocolRZAEBody() {
        return new PurchaseProtocolRZAE.Body();
    }

    /**
     * Create an instance of {@link ProtocolCancellation.Body }
     * 
     */
    public ProtocolCancellation.Body createProtocolCancellationBody() {
        return new ProtocolCancellation.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZK.Body }
     * 
     */
    public PurchaseNoticeZK.Body createPurchaseNoticeZKBody() {
        return new PurchaseNoticeZK.Body();
    }

    /**
     * Create an instance of {@link PurchaseNotice.Body }
     * 
     */
    public PurchaseNotice.Body createPurchaseNoticeBody() {
        return new PurchaseNotice.Body();
    }

    /**
     * Create an instance of {@link ExplanationRequest.Body }
     * 
     */
    public ExplanationRequest.Body createExplanationRequestBody() {
        return new ExplanationRequest.Body();
    }

    /**
     * Create an instance of {@link VolumeInnovPurchase.Body }
     * 
     */
    public VolumeInnovPurchase.Body createVolumeInnovPurchaseBody() {
        return new VolumeInnovPurchase.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE.Body }
     * 
     */
    public PurchaseProtocolPAAE.Body createPurchaseProtocolPAAEBody() {
        return new PurchaseProtocolPAAE.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOA.Body }
     * 
     */
    public PurchaseProtocolRZOA.Body createPurchaseProtocolRZOABody() {
        return new PurchaseProtocolRZOA.Body();
    }

    /**
     * Create an instance of {@link VolumeMonitoring.Body }
     * 
     */
    public VolumeMonitoring.Body createVolumeMonitoringBody() {
        return new VolumeMonitoring.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AE.Body }
     * 
     */
    public PurchaseProtocolRZ1AE.Body createPurchaseProtocolRZ1AEBody() {
        return new PurchaseProtocolRZ1AE.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOK.Body }
     * 
     */
    public PurchaseNoticeOK.Body createPurchaseNoticeOKBody() {
        return new PurchaseNoticeOK.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ2AE.Body }
     * 
     */
    public PurchaseProtocolRZ2AE.Body createPurchaseProtocolRZ2AEBody() {
        return new PurchaseProtocolRZ2AE.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE94FZ.Body }
     * 
     */
    public PurchaseNoticeAE94FZ.Body createPurchaseNoticeAE94FZBody() {
        return new PurchaseNoticeAE94FZ.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKESMBO.Body }
     * 
     */
    public PurchaseNoticeZKESMBO.Body createPurchaseNoticeZKESMBOBody() {
        return new PurchaseNoticeZKESMBO.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE.Body }
     * 
     */
    public PurchaseNoticeAE.Body createPurchaseNoticeAEBody() {
        return new PurchaseNoticeAE.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOK.Body }
     * 
     */
    public PurchaseProtocolRZOK.Body createPurchaseProtocolRZOKBody() {
        return new PurchaseProtocolRZOK.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE94FZ.Body }
     * 
     */
    public PurchaseProtocolPAAE94FZ.Body createPurchaseProtocolPAAE94FZBody() {
        return new PurchaseProtocolPAAE94FZ.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZPESMBO.Body }
     * 
     */
    public PurchaseNoticeZPESMBO.Body createPurchaseNoticeZPESMBOBody() {
        return new PurchaseNoticeZPESMBO.Body();
    }

    /**
     * Create an instance of {@link ListInnov.Body }
     * 
     */
    public ListInnov.Body createListInnovBody() {
        return new ListInnov.Body();
    }

    /**
     * Create an instance of {@link VolumePurchase.Body }
     * 
     */
    public VolumePurchase.Body createVolumePurchaseBody() {
        return new VolumePurchase.Body();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellation.Body }
     * 
     */
    public PurchaseLotCancellation.Body createPurchaseLotCancellationBody() {
        return new PurchaseLotCancellation.Body();
    }

    /**
     * Create an instance of {@link ListGWS.Body }
     * 
     */
    public ListGWS.Body createListGWSBody() {
        return new ListGWS.Body();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOA.Body }
     * 
     */
    public PurchaseNoticeOA.Body createPurchaseNoticeOABody() {
        return new PurchaseNoticeOA.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAEP.Body }
     * 
     */
    public PurchaseProtocolPAEP.Body createPurchaseProtocolPAEPBody() {
        return new PurchaseProtocolPAEP.Body();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZZKESMBOItemType }
     * 
     */
    public PurchaseProtocolRZZKESMBOItemType createPurchaseProtocolRZZKESMBOItemType() {
        return new PurchaseProtocolRZZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZPESMBOItemType }
     * 
     */
    public PurchaseNoticeZPESMBOItemType createPurchaseNoticeZPESMBOItemType() {
        return new PurchaseNoticeZPESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAESMBOItemType }
     * 
     */
    public PurchaseNoticeAESMBOItemType createPurchaseNoticeAESMBOItemType() {
        return new PurchaseNoticeAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionZPESMBODataType }
     * 
     */
    public PurchaseProtocolRejectionZPESMBODataType createPurchaseProtocolRejectionZPESMBODataType() {
        return new PurchaseProtocolRejectionZPESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseRejectionDataType }
     * 
     */
    public PurchaseRejectionDataType createPurchaseRejectionDataType() {
        return new PurchaseRejectionDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1ZPESMBODataType }
     * 
     */
    public PurchaseProtocolRZ1ZPESMBODataType createPurchaseProtocolRZ1ZPESMBODataType() {
        return new PurchaseProtocolRZ1ZPESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupZKESMBODataType }
     * 
     */
    public PurchaseProtocolSummingupZKESMBODataType createPurchaseProtocolSummingupZKESMBODataType() {
        return new PurchaseProtocolSummingupZKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAESMBODataType }
     * 
     */
    public PurchaseProtocolPAAESMBODataType createPurchaseProtocolPAAESMBODataType() {
        return new PurchaseProtocolPAAESMBODataType();
    }

    /**
     * Create an instance of {@link ProtocolPAAELotApplicationListType }
     * 
     */
    public ProtocolPAAELotApplicationListType createProtocolPAAELotApplicationListType() {
        return new ProtocolPAAELotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFCODKESMBODataType }
     * 
     */
    public PurchaseProtocolFCODKESMBODataType createPurchaseProtocolFCODKESMBODataType() {
        return new PurchaseProtocolFCODKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOKDataType }
     * 
     */
    public PurchaseNoticeOKDataType createPurchaseNoticeOKDataType() {
        return new PurchaseNoticeOKDataType();
    }

    /**
     * Create an instance of {@link ProtocolPAAELotApplications }
     * 
     */
    public ProtocolPAAELotApplications createProtocolPAAELotApplications() {
        return new ProtocolPAAELotApplications();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionKESMBOItemType }
     * 
     */
    public PurchaseProtocolRejectionKESMBOItemType createPurchaseProtocolRejectionKESMBOItemType() {
        return new PurchaseProtocolRejectionKESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZ2AEApplicationType }
     * 
     */
    public ProtocolRZ2AEApplicationType createProtocolRZ2AEApplicationType() {
        return new ProtocolRZ2AEApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionZPESMBODataType }
     * 
     */
    public PurchaseProtocolEvasionZPESMBODataType createPurchaseProtocolEvasionZPESMBODataType() {
        return new PurchaseProtocolEvasionZPESMBODataType();
    }

    /**
     * Create an instance of {@link VolumePurchaseData }
     * 
     */
    public VolumePurchaseData createVolumePurchaseData() {
        return new VolumePurchaseData();
    }

    /**
     * Create an instance of {@link PurchaseProtocolItemType }
     * 
     */
    public PurchaseProtocolItemType createPurchaseProtocolItemType() {
        return new PurchaseProtocolItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAESMBOItemType }
     * 
     */
    public PurchaseProtocolRZAESMBOItemType createPurchaseProtocolRZAESMBOItemType() {
        return new PurchaseProtocolRZAESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolPAAE94FZLotApplications }
     * 
     */
    public ProtocolPAAE94FZLotApplications createProtocolPAAE94FZLotApplications() {
        return new ProtocolPAAE94FZLotApplications();
    }

    /**
     * Create an instance of {@link VolumeInnovPurchaseData }
     * 
     */
    public VolumeInnovPurchaseData createVolumeInnovPurchaseData() {
        return new VolumeInnovPurchaseData();
    }

    /**
     * Create an instance of {@link PurchaseProtocolQSZPESMBODataType }
     * 
     */
    public PurchaseProtocolQSZPESMBODataType createPurchaseProtocolQSZPESMBODataType() {
        return new PurchaseProtocolQSZPESMBODataType();
    }

    /**
     * Create an instance of {@link ListInnovData }
     * 
     */
    public ListInnovData createListInnovData() {
        return new ListInnovData();
    }

    /**
     * Create an instance of {@link ProtocolLotApplicationListType }
     * 
     */
    public ProtocolLotApplicationListType createProtocolLotApplicationListType() {
        return new ProtocolLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1KESMBOItemType }
     * 
     */
    public PurchaseProtocolRZ1KESMBOItemType createPurchaseProtocolRZ1KESMBOItemType() {
        return new PurchaseProtocolRZ1KESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupZPESMBOItemType }
     * 
     */
    public PurchaseProtocolSummingupZPESMBOItemType createPurchaseProtocolSummingupZPESMBOItemType() {
        return new PurchaseProtocolSummingupZPESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFCDKESMBOItemType }
     * 
     */
    public PurchaseProtocolFCDKESMBOItemType createPurchaseProtocolFCDKESMBOItemType() {
        return new PurchaseProtocolFCDKESMBOItemType();
    }

    /**
     * Create an instance of {@link InnovPositionListType }
     * 
     */
    public InnovPositionListType createInnovPositionListType() {
        return new InnovPositionListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCZPESMBOItemType }
     * 
     */
    public PurchaseProtocolCCZPESMBOItemType createPurchaseProtocolCCZPESMBOItemType() {
        return new PurchaseProtocolCCZPESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolZKApplicationType }
     * 
     */
    public ProtocolZKApplicationType createProtocolZKApplicationType() {
        return new ProtocolZKApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCAESMBOItemType }
     * 
     */
    public PurchaseProtocolCCAESMBOItemType createPurchaseProtocolCCAESMBOItemType() {
        return new PurchaseProtocolCCAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseContractItemType }
     * 
     */
    public PurchaseContractItemType createPurchaseContractItemType() {
        return new PurchaseContractItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AESMBOItemType }
     * 
     */
    public PurchaseProtocolRZ1AESMBOItemType createPurchaseProtocolRZ1AESMBOItemType() {
        return new PurchaseProtocolRZ1AESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeDataBaseType }
     * 
     */
    public PurchaseNoticeDataBaseType createPurchaseNoticeDataBaseType() {
        return new PurchaseNoticeDataBaseType();
    }

    /**
     * Create an instance of {@link ChangeRequirementsItemType }
     * 
     */
    public ChangeRequirementsItemType createChangeRequirementsItemType() {
        return new ChangeRequirementsItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZPESMBODataType }
     * 
     */
    public PurchaseProtocolZPESMBODataType createPurchaseProtocolZPESMBODataType() {
        return new PurchaseProtocolZPESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCZKESMBODataType }
     * 
     */
    public PurchaseProtocolCCZKESMBODataType createPurchaseProtocolCCZKESMBODataType() {
        return new PurchaseProtocolCCZKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOAItemType }
     * 
     */
    public PurchaseNoticeOAItemType createPurchaseNoticeOAItemType() {
        return new PurchaseNoticeOAItemType();
    }

    /**
     * Create an instance of {@link ProtocolVKLotApplications }
     * 
     */
    public ProtocolVKLotApplications createProtocolVKLotApplications() {
        return new ProtocolVKLotApplications();
    }

    /**
     * Create an instance of {@link ProtocolRZ1AELotApplications }
     * 
     */
    public ProtocolRZ1AELotApplications createProtocolRZ1AELotApplications() {
        return new ProtocolRZ1AELotApplications();
    }

    /**
     * Create an instance of {@link AppliedDocumentsListType }
     * 
     */
    public AppliedDocumentsListType createAppliedDocumentsListType() {
        return new AppliedDocumentsListType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKESMBODataType }
     * 
     */
    public PurchaseNoticeZKESMBODataType createPurchaseNoticeZKESMBODataType() {
        return new PurchaseNoticeZKESMBODataType();
    }

    /**
     * Create an instance of {@link DocumentRequirementType }
     * 
     */
    public DocumentRequirementType createDocumentRequirementType() {
        return new DocumentRequirementType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeItemType }
     * 
     */
    public PurchaseNoticeItemType createPurchaseNoticeItemType() {
        return new PurchaseNoticeItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAEPItemType }
     * 
     */
    public PurchaseProtocolPAEPItemType createPurchaseProtocolPAEPItemType() {
        return new PurchaseProtocolPAEPItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZ1AELotApplicationListType }
     * 
     */
    public ProtocolRZ1AELotApplicationListType createProtocolRZ1AELotApplicationListType() {
        return new ProtocolRZ1AELotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCKESMBOItemType }
     * 
     */
    public PurchaseProtocolCCKESMBOItemType createPurchaseProtocolCCKESMBOItemType() {
        return new PurchaseProtocolCCKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOKItemType }
     * 
     */
    public PurchaseProtocolRZOKItemType createPurchaseProtocolRZOKItemType() {
        return new PurchaseProtocolRZOKItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAEDataType }
     * 
     */
    public PurchaseNoticeAEDataType createPurchaseNoticeAEDataType() {
        return new PurchaseNoticeAEDataType();
    }

    /**
     * Create an instance of {@link PurchaseContractAccountItemType }
     * 
     */
    public PurchaseContractAccountItemType createPurchaseContractAccountItemType() {
        return new PurchaseContractAccountItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeKESMBOItemType }
     * 
     */
    public PurchaseNoticeKESMBOItemType createPurchaseNoticeKESMBOItemType() {
        return new PurchaseNoticeKESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolPAEPApplicationType }
     * 
     */
    public ProtocolPAEPApplicationType createProtocolPAEPApplicationType() {
        return new ProtocolPAEPApplicationType();
    }

    /**
     * Create an instance of {@link ListGWSItemType }
     * 
     */
    public ListGWSItemType createListGWSItemType() {
        return new ListGWSItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupZKESMBOItemType }
     * 
     */
    public PurchaseProtocolSummingupZKESMBOItemType createPurchaseProtocolSummingupZKESMBOItemType() {
        return new PurchaseProtocolSummingupZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionKESMBODataType }
     * 
     */
    public PurchaseProtocolRejectionKESMBODataType createPurchaseProtocolRejectionKESMBODataType() {
        return new PurchaseProtocolRejectionKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCZPESMBODataType }
     * 
     */
    public PurchaseProtocolCCZPESMBODataType createPurchaseProtocolCCZPESMBODataType() {
        return new PurchaseProtocolCCZPESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAESMBOItemType }
     * 
     */
    public PurchaseProtocolPAAESMBOItemType createPurchaseProtocolPAAESMBOItemType() {
        return new PurchaseProtocolPAAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAESMBODataType }
     * 
     */
    public PurchaseNoticeAESMBODataType createPurchaseNoticeAESMBODataType() {
        return new PurchaseNoticeAESMBODataType();
    }

    /**
     * Create an instance of {@link ExplanationDataType }
     * 
     */
    public ExplanationDataType createExplanationDataType() {
        return new ExplanationDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOADataType }
     * 
     */
    public PurchaseProtocolRZOADataType createPurchaseProtocolRZOADataType() {
        return new PurchaseProtocolRZOADataType();
    }

    /**
     * Create an instance of {@link ProtocolPAOALotApplications }
     * 
     */
    public ProtocolPAOALotApplications createProtocolPAOALotApplications() {
        return new ProtocolPAOALotApplications();
    }

    /**
     * Create an instance of {@link ProtocolPAAE94FZApplicationType }
     * 
     */
    public ProtocolPAAE94FZApplicationType createProtocolPAAE94FZApplicationType() {
        return new ProtocolPAAE94FZApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOADataType }
     * 
     */
    public PurchaseNoticeOADataType createPurchaseNoticeOADataType() {
        return new PurchaseNoticeOADataType();
    }

    /**
     * Create an instance of {@link ExplanationRequestDataType }
     * 
     */
    public ExplanationRequestDataType createExplanationRequestDataType() {
        return new ExplanationRequestDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAEItemType }
     * 
     */
    public PurchaseProtocolRZAEItemType createPurchaseProtocolRZAEItemType() {
        return new PurchaseProtocolRZAEItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionZKESMBODataType }
     * 
     */
    public PurchaseProtocolRejectionZKESMBODataType createPurchaseProtocolRejectionZKESMBODataType() {
        return new PurchaseProtocolRejectionZKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupAESMBOItemType }
     * 
     */
    public PurchaseProtocolSummingupAESMBOItemType createPurchaseProtocolSummingupAESMBOItemType() {
        return new PurchaseProtocolSummingupAESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolVKLotApplicationListType }
     * 
     */
    public ProtocolVKLotApplicationListType createProtocolVKLotApplicationListType() {
        return new ProtocolVKLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolOSZItemType }
     * 
     */
    public PurchaseProtocolOSZItemType createPurchaseProtocolOSZItemType() {
        return new PurchaseProtocolOSZItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZOKLotApplicationListType }
     * 
     */
    public ProtocolRZOKLotApplicationListType createProtocolRZOKLotApplicationListType() {
        return new ProtocolRZOKLotApplicationListType();
    }

    /**
     * Create an instance of {@link ProtocolVKApplicationType }
     * 
     */
    public ProtocolVKApplicationType createProtocolVKApplicationType() {
        return new ProtocolVKApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZKItemType }
     * 
     */
    public PurchaseProtocolZKItemType createPurchaseProtocolZKItemType() {
        return new PurchaseProtocolZKItemType();
    }

    /**
     * Create an instance of {@link ProtocolPAOALotApplicationListType }
     * 
     */
    public ProtocolPAOALotApplicationListType createProtocolPAOALotApplicationListType() {
        return new ProtocolPAOALotApplicationListType();
    }

    /**
     * Create an instance of {@link ProtocolRZ1AEApplicationType }
     * 
     */
    public ProtocolRZ1AEApplicationType createProtocolRZ1AEApplicationType() {
        return new ProtocolRZ1AEApplicationType();
    }

    /**
     * Create an instance of {@link ProtocolOSZLotApplicationListType }
     * 
     */
    public ProtocolOSZLotApplicationListType createProtocolOSZLotApplicationListType() {
        return new ProtocolOSZLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKESMBOItemType }
     * 
     */
    public PurchaseNoticeZKESMBOItemType createPurchaseNoticeZKESMBOItemType() {
        return new PurchaseNoticeZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AESMBODataType }
     * 
     */
    public PurchaseProtocolRZ1AESMBODataType createPurchaseProtocolRZ1AESMBODataType() {
        return new PurchaseProtocolRZ1AESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAEItemType }
     * 
     */
    public PurchaseNoticeAEItemType createPurchaseNoticeAEItemType() {
        return new PurchaseNoticeAEItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolVKDataType }
     * 
     */
    public PurchaseProtocolVKDataType createPurchaseProtocolVKDataType() {
        return new PurchaseProtocolVKDataType();
    }

    /**
     * Create an instance of {@link ProtocolOSZApplicationType }
     * 
     */
    public ProtocolOSZApplicationType createProtocolOSZApplicationType() {
        return new ProtocolOSZApplicationType();
    }

    /**
     * Create an instance of {@link ContractItemsListType }
     * 
     */
    public ContractItemsListType createContractItemsListType() {
        return new ContractItemsListType();
    }

    /**
     * Create an instance of {@link ProtocolLotType }
     * 
     */
    public ProtocolLotType createProtocolLotType() {
        return new ProtocolLotType();
    }

    /**
     * Create an instance of {@link VolumeMonitoringData }
     * 
     */
    public VolumeMonitoringData createVolumeMonitoringData() {
        return new VolumeMonitoringData();
    }

    /**
     * Create an instance of {@link ProtocolPAAE94FZLotApplicationListType }
     * 
     */
    public ProtocolPAAE94FZLotApplicationListType createProtocolPAAE94FZLotApplicationListType() {
        return new ProtocolPAAE94FZLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFCDKESMBODataType }
     * 
     */
    public PurchaseProtocolFCDKESMBODataType createPurchaseProtocolFCDKESMBODataType() {
        return new PurchaseProtocolFCDKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFKVOKESMBOItemType }
     * 
     */
    public PurchaseProtocolFKVOKESMBOItemType createPurchaseProtocolFKVOKESMBOItemType() {
        return new PurchaseProtocolFKVOKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionAESMBOItemType }
     * 
     */
    public PurchaseProtocolRejectionAESMBOItemType createPurchaseProtocolRejectionAESMBOItemType() {
        return new PurchaseProtocolRejectionAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCKESMBODataType }
     * 
     */
    public PurchaseProtocolCCKESMBODataType createPurchaseProtocolCCKESMBODataType() {
        return new PurchaseProtocolCCKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeNonISBaseType }
     * 
     */
    public PurchaseNoticeNonISBaseType createPurchaseNoticeNonISBaseType() {
        return new PurchaseNoticeNonISBaseType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAEPDataType }
     * 
     */
    public PurchaseProtocolPAEPDataType createPurchaseProtocolPAEPDataType() {
        return new PurchaseProtocolPAEPDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionAESMBOItemType }
     * 
     */
    public PurchaseProtocolEvasionAESMBOItemType createPurchaseProtocolEvasionAESMBOItemType() {
        return new PurchaseProtocolEvasionAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionZPESMBOItemType }
     * 
     */
    public PurchaseProtocolRejectionZPESMBOItemType createPurchaseProtocolRejectionZPESMBOItemType() {
        return new PurchaseProtocolRejectionZPESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolZKLotApplications }
     * 
     */
    public ProtocolZKLotApplications createProtocolZKLotApplications() {
        return new ProtocolZKLotApplications();
    }

    /**
     * Create an instance of {@link LotParameters }
     * 
     */
    public LotParameters createLotParameters() {
        return new LotParameters();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOKDataType }
     * 
     */
    public PurchaseProtocolRZOKDataType createPurchaseProtocolRZOKDataType() {
        return new PurchaseProtocolRZOKDataType();
    }

    /**
     * Create an instance of {@link ChangeRequirementsDataType }
     * 
     */
    public ChangeRequirementsDataType createChangeRequirementsDataType() {
        return new ChangeRequirementsDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionKESMBODataType }
     * 
     */
    public PurchaseProtocolEvasionKESMBODataType createPurchaseProtocolEvasionKESMBODataType() {
        return new PurchaseProtocolEvasionKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolVKItemType }
     * 
     */
    public PurchaseProtocolVKItemType createPurchaseProtocolVKItemType() {
        return new PurchaseProtocolVKItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZOAItemType }
     * 
     */
    public PurchaseProtocolRZOAItemType createPurchaseProtocolRZOAItemType() {
        return new PurchaseProtocolRZOAItemType();
    }

    /**
     * Create an instance of {@link ExplanationItemType }
     * 
     */
    public ExplanationItemType createExplanationItemType() {
        return new ExplanationItemType();
    }

    /**
     * Create an instance of {@link ProtocolPAEPLotApplicationListType }
     * 
     */
    public ProtocolPAEPLotApplicationListType createProtocolPAEPLotApplicationListType() {
        return new ProtocolPAEPLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupKESMBODataType }
     * 
     */
    public PurchaseProtocolSummingupKESMBODataType createPurchaseProtocolSummingupKESMBODataType() {
        return new PurchaseProtocolSummingupKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCAESMBODataType }
     * 
     */
    public PurchaseProtocolCCAESMBODataType createPurchaseProtocolCCAESMBODataType() {
        return new PurchaseProtocolCCAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AEItemType }
     * 
     */
    public PurchaseProtocolRZ1AEItemType createPurchaseProtocolRZ1AEItemType() {
        return new PurchaseProtocolRZ1AEItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolOSZDataType }
     * 
     */
    public PurchaseProtocolOSZDataType createPurchaseProtocolOSZDataType() {
        return new PurchaseProtocolOSZDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZKDataType }
     * 
     */
    public PurchaseProtocolZKDataType createPurchaseProtocolZKDataType() {
        return new PurchaseProtocolZKDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAEDataType }
     * 
     */
    public PurchaseProtocolPAAEDataType createPurchaseProtocolPAAEDataType() {
        return new PurchaseProtocolPAAEDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCCZKESMBOItemType }
     * 
     */
    public PurchaseProtocolCCZKESMBOItemType createPurchaseProtocolCCZKESMBOItemType() {
        return new PurchaseProtocolCCZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionZKESMBODataType }
     * 
     */
    public PurchaseProtocolEvasionZKESMBODataType createPurchaseProtocolEvasionZKESMBODataType() {
        return new PurchaseProtocolEvasionZKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupZPESMBODataType }
     * 
     */
    public PurchaseProtocolSummingupZPESMBODataType createPurchaseProtocolSummingupZPESMBODataType() {
        return new PurchaseProtocolSummingupZPESMBODataType();
    }

    /**
     * Create an instance of {@link ProtocolRZ2AELotApplicationListType }
     * 
     */
    public ProtocolRZ2AELotApplicationListType createProtocolRZ2AELotApplicationListType() {
        return new ProtocolRZ2AELotApplicationListType();
    }

    /**
     * Create an instance of {@link GwsPositionType }
     * 
     */
    public GwsPositionType createGwsPositionType() {
        return new GwsPositionType();
    }

    /**
     * Create an instance of {@link ListGWSData }
     * 
     */
    public ListGWSData createListGWSData() {
        return new ListGWSData();
    }

    /**
     * Create an instance of {@link VolumePurchaseItemType }
     * 
     */
    public VolumePurchaseItemType createVolumePurchaseItemType() {
        return new VolumePurchaseItemType();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocationItemType }
     * 
     */
    public ProtocolLotAllocationItemType createProtocolLotAllocationItemType() {
        return new ProtocolLotAllocationItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAEDataType }
     * 
     */
    public PurchaseProtocolRZAEDataType createPurchaseProtocolRZAEDataType() {
        return new PurchaseProtocolRZAEDataType();
    }

    /**
     * Create an instance of {@link ProtocolPAEPLotApplications }
     * 
     */
    public ProtocolPAEPLotApplications createProtocolPAEPLotApplications() {
        return new ProtocolPAEPLotApplications();
    }

    /**
     * Create an instance of {@link VolumeMonitoringItemType }
     * 
     */
    public VolumeMonitoringItemType createVolumeMonitoringItemType() {
        return new VolumeMonitoringItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZ2AELotApplications }
     * 
     */
    public ProtocolRZ2AELotApplications createProtocolRZ2AELotApplications() {
        return new ProtocolRZ2AELotApplications();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ2AEItemType }
     * 
     */
    public PurchaseProtocolRZ2AEItemType createPurchaseProtocolRZ2AEItemType() {
        return new PurchaseProtocolRZ2AEItemType();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellationItemType }
     * 
     */
    public PurchaseLotCancellationItemType createPurchaseLotCancellationItemType() {
        return new PurchaseLotCancellationItemType();
    }

    /**
     * Create an instance of {@link MonitoringIndicatorType }
     * 
     */
    public MonitoringIndicatorType createMonitoringIndicatorType() {
        return new MonitoringIndicatorType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionZPESMBOItemType }
     * 
     */
    public PurchaseProtocolEvasionZPESMBOItemType createPurchaseProtocolEvasionZPESMBOItemType() {
        return new PurchaseProtocolEvasionZPESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKDataType }
     * 
     */
    public PurchaseNoticeZKDataType createPurchaseNoticeZKDataType() {
        return new PurchaseNoticeZKDataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeEPItemType }
     * 
     */
    public PurchaseNoticeEPItemType createPurchaseNoticeEPItemType() {
        return new PurchaseNoticeEPItemType();
    }

    /**
     * Create an instance of {@link ProtocolZKLotApplicationListType }
     * 
     */
    public ProtocolZKLotApplicationListType createProtocolZKLotApplicationListType() {
        return new ProtocolZKLotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE94FZItemType }
     * 
     */
    public PurchaseNoticeAE94FZItemType createPurchaseNoticeAE94FZItemType() {
        return new PurchaseNoticeAE94FZItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZOALotApplicationListType }
     * 
     */
    public ProtocolRZOALotApplicationListType createProtocolRZOALotApplicationListType() {
        return new ProtocolRZOALotApplicationListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1ZPESMBOItemType }
     * 
     */
    public PurchaseProtocolRZ1ZPESMBOItemType createPurchaseProtocolRZ1ZPESMBOItemType() {
        return new PurchaseProtocolRZ1ZPESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolRZOALotApplications }
     * 
     */
    public ProtocolRZOALotApplications createProtocolRZOALotApplications() {
        return new ProtocolRZOALotApplications();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCollationAESMBODataType }
     * 
     */
    public PurchaseProtocolCollationAESMBODataType createPurchaseProtocolCollationAESMBODataType() {
        return new PurchaseProtocolCollationAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionZKESMBOItemType }
     * 
     */
    public PurchaseProtocolRejectionZKESMBOItemType createPurchaseProtocolRejectionZKESMBOItemType() {
        return new PurchaseProtocolRejectionZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE94FZDataType }
     * 
     */
    public PurchaseProtocolPAAE94FZDataType createPurchaseProtocolPAAE94FZDataType() {
        return new PurchaseProtocolPAAE94FZDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAOAItemType }
     * 
     */
    public PurchaseProtocolPAOAItemType createPurchaseProtocolPAOAItemType() {
        return new PurchaseProtocolPAOAItemType();
    }

    /**
     * Create an instance of {@link ExplanationRequestItemType }
     * 
     */
    public ExplanationRequestItemType createExplanationRequestItemType() {
        return new ExplanationRequestItemType();
    }

    /**
     * Create an instance of {@link VolumeInnovPurchaseItemType }
     * 
     */
    public VolumeInnovPurchaseItemType createVolumeInnovPurchaseItemType() {
        return new VolumeInnovPurchaseItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZZKESMBODataType }
     * 
     */
    public PurchaseProtocolRZZKESMBODataType createPurchaseProtocolRZZKESMBODataType() {
        return new PurchaseProtocolRZZKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolQSAESMBOItemType }
     * 
     */
    public PurchaseProtocolQSAESMBOItemType createPurchaseProtocolQSAESMBOItemType() {
        return new PurchaseProtocolQSAESMBOItemType();
    }

    /**
     * Create an instance of {@link ProtocolApplicationType }
     * 
     */
    public ProtocolApplicationType createProtocolApplicationType() {
        return new ProtocolApplicationType();
    }

    /**
     * Create an instance of {@link ListInnovItemType }
     * 
     */
    public ListInnovItemType createListInnovItemType() {
        return new ListInnovItemType();
    }

    /**
     * Create an instance of {@link ProtocolCancellationType }
     * 
     */
    public ProtocolCancellationType createProtocolCancellationType() {
        return new ProtocolCancellationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionAESMBODataType }
     * 
     */
    public PurchaseProtocolEvasionAESMBODataType createPurchaseProtocolEvasionAESMBODataType() {
        return new PurchaseProtocolEvasionAESMBODataType();
    }

    /**
     * Create an instance of {@link ProtocolOSZLotApplications }
     * 
     */
    public ProtocolOSZLotApplications createProtocolOSZLotApplications() {
        return new ProtocolOSZLotApplications();
    }

    /**
     * Create an instance of {@link MonitoringIndicatorListType }
     * 
     */
    public MonitoringIndicatorListType createMonitoringIndicatorListType() {
        return new MonitoringIndicatorListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFKVOKESMBODataType }
     * 
     */
    public PurchaseProtocolFKVOKESMBODataType createPurchaseProtocolFKVOKESMBODataType() {
        return new PurchaseProtocolFKVOKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRejectionAESMBODataType }
     * 
     */
    public PurchaseProtocolRejectionAESMBODataType createPurchaseProtocolRejectionAESMBODataType() {
        return new PurchaseProtocolRejectionAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupAESMBODataType }
     * 
     */
    public PurchaseProtocolSummingupAESMBODataType createPurchaseProtocolSummingupAESMBODataType() {
        return new PurchaseProtocolSummingupAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolQSAESMBODataType }
     * 
     */
    public PurchaseProtocolQSAESMBODataType createPurchaseProtocolQSAESMBODataType() {
        return new PurchaseProtocolQSAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionZKESMBOItemType }
     * 
     */
    public PurchaseProtocolEvasionZKESMBOItemType createPurchaseProtocolEvasionZKESMBOItemType() {
        return new PurchaseProtocolEvasionZKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeOKItemType }
     * 
     */
    public PurchaseNoticeOKItemType createPurchaseNoticeOKItemType() {
        return new PurchaseNoticeOKItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolZPESMBOItemType }
     * 
     */
    public PurchaseProtocolZPESMBOItemType createPurchaseProtocolZPESMBOItemType() {
        return new PurchaseProtocolZPESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeEPDataType }
     * 
     */
    public PurchaseNoticeEPDataType createPurchaseNoticeEPDataType() {
        return new PurchaseNoticeEPDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1AEDataType }
     * 
     */
    public PurchaseProtocolRZ1AEDataType createPurchaseProtocolRZ1AEDataType() {
        return new PurchaseProtocolRZ1AEDataType();
    }

    /**
     * Create an instance of {@link ProtocolPAOAApplicationType }
     * 
     */
    public ProtocolPAOAApplicationType createProtocolPAOAApplicationType() {
        return new ProtocolPAOAApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolFCODKESMBOItemType }
     * 
     */
    public PurchaseProtocolFCODKESMBOItemType createPurchaseProtocolFCODKESMBOItemType() {
        return new PurchaseProtocolFCODKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAEItemType }
     * 
     */
    public PurchaseProtocolPAAEItemType createPurchaseProtocolPAAEItemType() {
        return new PurchaseProtocolPAAEItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolQSZPESMBOItemType }
     * 
     */
    public PurchaseProtocolQSZPESMBOItemType createPurchaseProtocolQSZPESMBOItemType() {
        return new PurchaseProtocolQSZPESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZKItemType }
     * 
     */
    public PurchaseNoticeZKItemType createPurchaseNoticeZKItemType() {
        return new PurchaseNoticeZKItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZAESMBODataType }
     * 
     */
    public PurchaseProtocolRZAESMBODataType createPurchaseProtocolRZAESMBODataType() {
        return new PurchaseProtocolRZAESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseRejectionType }
     * 
     */
    public PurchaseRejectionType createPurchaseRejectionType() {
        return new PurchaseRejectionType();
    }

    /**
     * Create an instance of {@link InnovPositionType }
     * 
     */
    public InnovPositionType createInnovPositionType() {
        return new InnovPositionType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ2AEDataType }
     * 
     */
    public PurchaseProtocolRZ2AEDataType createPurchaseProtocolRZ2AEDataType() {
        return new PurchaseProtocolRZ2AEDataType();
    }

    /**
     * Create an instance of {@link ProtocolRZOKLotApplications }
     * 
     */
    public ProtocolRZOKLotApplications createProtocolRZOKLotApplications() {
        return new ProtocolRZOKLotApplications();
    }

    /**
     * Create an instance of {@link GwsPositionListType }
     * 
     */
    public GwsPositionListType createGwsPositionListType() {
        return new GwsPositionListType();
    }

    /**
     * Create an instance of {@link ProtocolRZOKApplicationType }
     * 
     */
    public ProtocolRZOKApplicationType createProtocolRZOKApplicationType() {
        return new ProtocolRZOKApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolBaseDataType }
     * 
     */
    public PurchaseProtocolBaseDataType createPurchaseProtocolBaseDataType() {
        return new PurchaseProtocolBaseDataType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAOADataType }
     * 
     */
    public PurchaseProtocolPAOADataType createPurchaseProtocolPAOADataType() {
        return new PurchaseProtocolPAOADataType();
    }

    /**
     * Create an instance of {@link MonitoringInconsistencyListType }
     * 
     */
    public MonitoringInconsistencyListType createMonitoringInconsistencyListType() {
        return new MonitoringInconsistencyListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolCollationAESMBOItemType }
     * 
     */
    public PurchaseProtocolCollationAESMBOItemType createPurchaseProtocolCollationAESMBOItemType() {
        return new PurchaseProtocolCollationAESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolPAAE94FZItemType }
     * 
     */
    public PurchaseProtocolPAAE94FZItemType createPurchaseProtocolPAAE94FZItemType() {
        return new PurchaseProtocolPAAE94FZItemType();
    }

    /**
     * Create an instance of {@link PurchaseIndicatorType }
     * 
     */
    public PurchaseIndicatorType createPurchaseIndicatorType() {
        return new PurchaseIndicatorType();
    }

    /**
     * Create an instance of {@link MonitoringInconsistencyType }
     * 
     */
    public MonitoringInconsistencyType createMonitoringInconsistencyType() {
        return new MonitoringInconsistencyType();
    }

    /**
     * Create an instance of {@link ProtocolPAAEApplicationType }
     * 
     */
    public ProtocolPAAEApplicationType createProtocolPAAEApplicationType() {
        return new ProtocolPAAEApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolSummingupKESMBOItemType }
     * 
     */
    public PurchaseProtocolSummingupKESMBOItemType createPurchaseProtocolSummingupKESMBOItemType() {
        return new PurchaseProtocolSummingupKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseContractDataType }
     * 
     */
    public PurchaseContractDataType createPurchaseContractDataType() {
        return new PurchaseContractDataType();
    }

    /**
     * Create an instance of {@link ProtocolRZOAApplicationType }
     * 
     */
    public ProtocolRZOAApplicationType createProtocolRZOAApplicationType() {
        return new ProtocolRZOAApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseIndicatorListType }
     * 
     */
    public PurchaseIndicatorListType createPurchaseIndicatorListType() {
        return new PurchaseIndicatorListType();
    }

    /**
     * Create an instance of {@link PurchaseProtocolEvasionKESMBOItemType }
     * 
     */
    public PurchaseProtocolEvasionKESMBOItemType createPurchaseProtocolEvasionKESMBOItemType() {
        return new PurchaseProtocolEvasionKESMBOItemType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeZPESMBODataType }
     * 
     */
    public PurchaseNoticeZPESMBODataType createPurchaseNoticeZPESMBODataType() {
        return new PurchaseNoticeZPESMBODataType();
    }

    /**
     * Create an instance of {@link ProtocolLotApplications }
     * 
     */
    public ProtocolLotApplications createProtocolLotApplications() {
        return new ProtocolLotApplications();
    }

    /**
     * Create an instance of {@link PurchaseProtocolRZ1KESMBODataType }
     * 
     */
    public PurchaseProtocolRZ1KESMBODataType createPurchaseProtocolRZ1KESMBODataType() {
        return new PurchaseProtocolRZ1KESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseContractAccountDataType }
     * 
     */
    public PurchaseContractAccountDataType createPurchaseContractAccountDataType() {
        return new PurchaseContractAccountDataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeKESMBODataType }
     * 
     */
    public PurchaseNoticeKESMBODataType createPurchaseNoticeKESMBODataType() {
        return new PurchaseNoticeKESMBODataType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeAE94FZDataType }
     * 
     */
    public PurchaseNoticeAE94FZDataType createPurchaseNoticeAE94FZDataType() {
        return new PurchaseNoticeAE94FZDataType();
    }

    /**
     * Create an instance of {@link AppliedDocumentType }
     * 
     */
    public AppliedDocumentType createAppliedDocumentType() {
        return new AppliedDocumentType();
    }

    /**
     * Create an instance of {@link PurchaseNoticeDataType.PlacingProcedure }
     * 
     */
    public PurchaseNoticeDataType.PlacingProcedure createPurchaseNoticeDataTypePlacingProcedure() {
        return new PurchaseNoticeDataType.PlacingProcedure();
    }

    /**
     * Create an instance of {@link PurchaseNoticeDataType.TemplateStructure.Level }
     * 
     */
    public PurchaseNoticeDataType.TemplateStructure.Level createPurchaseNoticeDataTypeTemplateStructureLevel() {
        return new PurchaseNoticeDataType.TemplateStructure.Level();
    }

    /**
     * Create an instance of {@link ProtocolLotAllocationData.AllocatedLots.AllocatedLot }
     * 
     */
    public ProtocolLotAllocationData.AllocatedLots.AllocatedLot createProtocolLotAllocationDataAllocatedLotsAllocatedLot() {
        return new ProtocolLotAllocationData.AllocatedLots.AllocatedLot();
    }

    /**
     * Create an instance of {@link PurchaseLotCancellationData.CancelledLots.CancelledLot }
     * 
     */
    public PurchaseLotCancellationData.CancelledLots.CancelledLot createPurchaseLotCancellationDataCancelledLotsCancelledLot() {
        return new PurchaseLotCancellationData.CancelledLots.CancelledLot();
    }

    /**
     * Create an instance of {@link PurchaseProtocolDataType.TemplateStructure.Level }
     * 
     */
    public PurchaseProtocolDataType.TemplateStructure.Level createPurchaseProtocolDataTypeTemplateStructureLevel() {
        return new PurchaseProtocolDataType.TemplateStructure.Level();
    }

    /**
     * Create an instance of {@link ProtocolCancellationDataType.ProtocolInfo }
     * 
     */
    public ProtocolCancellationDataType.ProtocolInfo createProtocolCancellationDataTypeProtocolInfo() {
        return new ProtocolCancellationDataType.ProtocolInfo();
    }

}
