//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:09:17 PM MSK 
//


package ru.gov.zakupki._223fz.purchase._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ru.gov.zakupki._223fz.types._1.SupplierMainInfoType;
import ru.gov.zakupki._223fz.types._1.WinnerIndication2;


/**
 * Результат оценки и сопоставления заявок
 * 
 * <p>Java class for protocolOSZApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protocolOSZApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="supplierInfo" type="{http://zakupki.gov.ru/223fz/types/1}supplierMainInfoType"/>
 *         &lt;element name="applicationResult" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="applicationRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="applicationPlace" type="{http://zakupki.gov.ru/223fz/types/1}winnerIndication2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protocolOSZApplicationType", propOrder = {
    "applicationNumber",
    "supplierInfo",
    "applicationResult",
    "applicationRate",
    "applicationPlace"
})
public class ProtocolOSZApplicationType {

    @XmlElement(required = true)
    protected String applicationNumber;
    @XmlElement(required = true)
    protected SupplierMainInfoType supplierInfo;
    @XmlElement(required = true)
    protected BigDecimal applicationResult;
    protected int applicationRate;
    @XmlSchemaType(name = "string")
    protected WinnerIndication2 applicationPlace;

    /**
     * Gets the value of the applicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * Sets the value of the applicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationNumber(String value) {
        this.applicationNumber = value;
    }

    /**
     * Gets the value of the supplierInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierMainInfoType }
     *     
     */
    public SupplierMainInfoType getSupplierInfo() {
        return supplierInfo;
    }

    /**
     * Sets the value of the supplierInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierMainInfoType }
     *     
     */
    public void setSupplierInfo(SupplierMainInfoType value) {
        this.supplierInfo = value;
    }

    /**
     * Gets the value of the applicationResult property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApplicationResult() {
        return applicationResult;
    }

    /**
     * Sets the value of the applicationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApplicationResult(BigDecimal value) {
        this.applicationResult = value;
    }

    /**
     * Gets the value of the applicationRate property.
     * 
     */
    public int getApplicationRate() {
        return applicationRate;
    }

    /**
     * Sets the value of the applicationRate property.
     * 
     */
    public void setApplicationRate(int value) {
        this.applicationRate = value;
    }

    /**
     * Gets the value of the applicationPlace property.
     * 
     * @return
     *     possible object is
     *     {@link WinnerIndication2 }
     *     
     */
    public WinnerIndication2 getApplicationPlace() {
        return applicationPlace;
    }

    /**
     * Sets the value of the applicationPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link WinnerIndication2 }
     *     
     */
    public void setApplicationPlace(WinnerIndication2 value) {
        this.applicationPlace = value;
    }

}
