//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:11:07 PM MSK 
//


package ru.gov.zakupki._223fz.purchase._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki._223fz.types._1.ElectronicPlaceInfoType;
import ru.gov.zakupki._223fz.types._1.LotISListType;
import ru.gov.zakupki._223fz.types._1.NonelectronicPlaceInfoType;
import ru.gov.zakupki._223fz.types._1.NoticeTemplateFieldValueListType;


/**
 * Извещение о закупке "Иной способ"
 * 
 * <p>Java class for purchaseNoticeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeDataBaseType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="electronicPlaceInfo">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://zakupki.gov.ru/223fz/types/1}electronicPlaceInfoType">
 *                   &lt;sequence>
 *                     &lt;element name="purchaseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;/sequence>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="nonelectronicPlaceInfo" type="{http://zakupki.gov.ru/223fz/types/1}nonelectronicPlaceInfoType"/>
 *         &lt;/choice>
 *         &lt;element name="examinationPlace">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="examinationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="submissionCloseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="publicationPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="templateVersion" type="{http://zakupki.gov.ru/223fz/types/1}templateVersionType" minOccurs="0"/>
 *         &lt;element name="extendFields" type="{http://zakupki.gov.ru/223fz/types/1}noticeTemplateFieldValueListType" minOccurs="0"/>
 *         &lt;element name="lots" type="{http://zakupki.gov.ru/223fz/types/1}lotISListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeDataType", propOrder = {
    "electronicPlaceInfo",
    "nonelectronicPlaceInfo",
    "examinationPlace",
    "examinationDateTime",
    "submissionCloseDateTime",
    "publicationPlannedDate",
    "templateVersion",
    "extendFields",
    "lots"
})
public class PurchaseNoticeDataType
    extends PurchaseNoticeDataBaseType
{

    protected PurchaseNoticeDataType.ElectronicPlaceInfo electronicPlaceInfo;
    protected NonelectronicPlaceInfoType nonelectronicPlaceInfo;
    @XmlElement(required = true)
    protected String examinationPlace;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar examinationDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionCloseDateTime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar publicationPlannedDate;
    protected Long templateVersion;
    protected NoticeTemplateFieldValueListType extendFields;
    protected LotISListType lots;

    /**
     * Gets the value of the electronicPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseNoticeDataType.ElectronicPlaceInfo }
     *     
     */
    public PurchaseNoticeDataType.ElectronicPlaceInfo getElectronicPlaceInfo() {
        return electronicPlaceInfo;
    }

    /**
     * Sets the value of the electronicPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseNoticeDataType.ElectronicPlaceInfo }
     *     
     */
    public void setElectronicPlaceInfo(PurchaseNoticeDataType.ElectronicPlaceInfo value) {
        this.electronicPlaceInfo = value;
    }

    /**
     * Gets the value of the nonelectronicPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NonelectronicPlaceInfoType }
     *     
     */
    public NonelectronicPlaceInfoType getNonelectronicPlaceInfo() {
        return nonelectronicPlaceInfo;
    }

    /**
     * Sets the value of the nonelectronicPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonelectronicPlaceInfoType }
     *     
     */
    public void setNonelectronicPlaceInfo(NonelectronicPlaceInfoType value) {
        this.nonelectronicPlaceInfo = value;
    }

    /**
     * Gets the value of the examinationPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminationPlace() {
        return examinationPlace;
    }

    /**
     * Sets the value of the examinationPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminationPlace(String value) {
        this.examinationPlace = value;
    }

    /**
     * Gets the value of the examinationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExaminationDateTime() {
        return examinationDateTime;
    }

    /**
     * Sets the value of the examinationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExaminationDateTime(XMLGregorianCalendar value) {
        this.examinationDateTime = value;
    }

    /**
     * Gets the value of the submissionCloseDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionCloseDateTime() {
        return submissionCloseDateTime;
    }

    /**
     * Sets the value of the submissionCloseDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionCloseDateTime(XMLGregorianCalendar value) {
        this.submissionCloseDateTime = value;
    }

    /**
     * Gets the value of the publicationPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationPlannedDate() {
        return publicationPlannedDate;
    }

    /**
     * Sets the value of the publicationPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationPlannedDate(XMLGregorianCalendar value) {
        this.publicationPlannedDate = value;
    }

    /**
     * Gets the value of the templateVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTemplateVersion() {
        return templateVersion;
    }

    /**
     * Sets the value of the templateVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTemplateVersion(Long value) {
        this.templateVersion = value;
    }

    /**
     * Gets the value of the extendFields property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeTemplateFieldValueListType }
     *     
     */
    public NoticeTemplateFieldValueListType getExtendFields() {
        return extendFields;
    }

    /**
     * Sets the value of the extendFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeTemplateFieldValueListType }
     *     
     */
    public void setExtendFields(NoticeTemplateFieldValueListType value) {
        this.extendFields = value;
    }

    /**
     * Gets the value of the lots property.
     * 
     * @return
     *     possible object is
     *     {@link LotISListType }
     *     
     */
    public LotISListType getLots() {
        return lots;
    }

    /**
     * Sets the value of the lots property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotISListType }
     *     
     */
    public void setLots(LotISListType value) {
        this.lots = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://zakupki.gov.ru/223fz/types/1}electronicPlaceInfoType">
     *       &lt;sequence>
     *         &lt;element name="purchaseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "purchaseDateTime"
    })
    public static class ElectronicPlaceInfo
        extends ElectronicPlaceInfoType
    {

        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar purchaseDateTime;

        /**
         * Gets the value of the purchaseDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPurchaseDateTime() {
            return purchaseDateTime;
        }

        /**
         * Sets the value of the purchaseDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPurchaseDateTime(XMLGregorianCalendar value) {
            this.purchaseDateTime = value;
        }

    }

}
