//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 04:59:41 PM MSK 
//


package ru.gov.zakupki._223fz.purchase._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Извещение о закупке "Запрос предложений в электронной форме, участниками которого могут являться только субъекты малого и среднего предпринимательства"
 * 
 * <p>Java class for purchaseNoticeZPESMBODataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeZPESMBODataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeNonISBaseType">
 *       &lt;sequence>
 *         &lt;element name="considerationFirstPartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="considerationFirstPartPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="considerationFirstPartOrder" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="considerationSecondPartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="summingupDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="summingupPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="submissionCloseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="publicationPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="documentsRequirement" type="{http://zakupki.gov.ru/223fz/purchase/1}documentRequirementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeZPESMBODataType", propOrder = {
    "considerationFirstPartDate",
    "considerationFirstPartPlace",
    "considerationFirstPartOrder",
    "considerationSecondPartDate",
    "summingupDate",
    "summingupPlace",
    "submissionCloseDateTime",
    "publicationPlannedDate",
    "documentsRequirement"
})
public class PurchaseNoticeZPESMBODataType
    extends PurchaseNoticeNonISBaseType
{

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar considerationFirstPartDate;
    protected String considerationFirstPartPlace;
    protected String considerationFirstPartOrder;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar considerationSecondPartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar summingupDate;
    protected String summingupPlace;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionCloseDateTime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar publicationPlannedDate;
    protected List<DocumentRequirementType> documentsRequirement;

    /**
     * Gets the value of the considerationFirstPartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConsiderationFirstPartDate() {
        return considerationFirstPartDate;
    }

    /**
     * Sets the value of the considerationFirstPartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConsiderationFirstPartDate(XMLGregorianCalendar value) {
        this.considerationFirstPartDate = value;
    }

    /**
     * Gets the value of the considerationFirstPartPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsiderationFirstPartPlace() {
        return considerationFirstPartPlace;
    }

    /**
     * Sets the value of the considerationFirstPartPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsiderationFirstPartPlace(String value) {
        this.considerationFirstPartPlace = value;
    }

    /**
     * Gets the value of the considerationFirstPartOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsiderationFirstPartOrder() {
        return considerationFirstPartOrder;
    }

    /**
     * Sets the value of the considerationFirstPartOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsiderationFirstPartOrder(String value) {
        this.considerationFirstPartOrder = value;
    }

    /**
     * Gets the value of the considerationSecondPartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConsiderationSecondPartDate() {
        return considerationSecondPartDate;
    }

    /**
     * Sets the value of the considerationSecondPartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConsiderationSecondPartDate(XMLGregorianCalendar value) {
        this.considerationSecondPartDate = value;
    }

    /**
     * Gets the value of the summingupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSummingupDate() {
        return summingupDate;
    }

    /**
     * Sets the value of the summingupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSummingupDate(XMLGregorianCalendar value) {
        this.summingupDate = value;
    }

    /**
     * Gets the value of the summingupPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummingupPlace() {
        return summingupPlace;
    }

    /**
     * Sets the value of the summingupPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummingupPlace(String value) {
        this.summingupPlace = value;
    }

    /**
     * Gets the value of the submissionCloseDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionCloseDateTime() {
        return submissionCloseDateTime;
    }

    /**
     * Sets the value of the submissionCloseDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionCloseDateTime(XMLGregorianCalendar value) {
        this.submissionCloseDateTime = value;
    }

    /**
     * Gets the value of the publicationPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationPlannedDate() {
        return publicationPlannedDate;
    }

    /**
     * Sets the value of the publicationPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationPlannedDate(XMLGregorianCalendar value) {
        this.publicationPlannedDate = value;
    }

    /**
     * Gets the value of the documentsRequirement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentsRequirement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentsRequirement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentRequirementType }
     * 
     * 
     */
    public List<DocumentRequirementType> getDocumentsRequirement() {
        if (documentsRequirement == null) {
            documentsRequirement = new ArrayList<DocumentRequirementType>();
        }
        return this.documentsRequirement;
    }

}
