//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:17:00 PM MSK 
//


package ru.gov.zakupki._223fz.purchase._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki._223fz.types._1.ElectronicPlaceInfoType;
import ru.gov.zakupki._223fz.types._1.LotISListType;
import ru.gov.zakupki._223fz.types._1.NoticeTemplateFieldValueListType;


/**
 * Извещение о закупке "Иной способ"
 * 
 * <p>Java class for purchaseNoticeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeDataBaseType">
 *       &lt;sequence>
 *         &lt;element name="electronicPlaceInfo" type="{http://zakupki.gov.ru/223fz/types/1}electronicPlaceInfoType" minOccurs="0"/>
 *         &lt;element name="placingProcedure" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="examinationPlace">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="2000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="examinationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="summingupDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="summingupPlace" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="2000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="submissionCloseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="publicationPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="templateVersion" type="{http://zakupki.gov.ru/223fz/types/1}templateVersionType" minOccurs="0"/>
 *         &lt;element name="extendFields" type="{http://zakupki.gov.ru/223fz/types/1}noticeTemplateFieldValueListType" minOccurs="0"/>
 *         &lt;element name="lots" type="{http://zakupki.gov.ru/223fz/types/1}lotISListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeDataType", propOrder = {
    "electronicPlaceInfo",
    "placingProcedure",
    "submissionCloseDateTime",
    "publicationPlannedDate",
    "templateVersion",
    "extendFields",
    "lots"
})
public class PurchaseNoticeDataType
    extends PurchaseNoticeDataBaseType
{

    protected ElectronicPlaceInfoType electronicPlaceInfo;
    protected PurchaseNoticeDataType.PlacingProcedure placingProcedure;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionCloseDateTime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar publicationPlannedDate;
    protected Long templateVersion;
    protected NoticeTemplateFieldValueListType extendFields;
    protected LotISListType lots;

    /**
     * Gets the value of the electronicPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public ElectronicPlaceInfoType getElectronicPlaceInfo() {
        return electronicPlaceInfo;
    }

    /**
     * Sets the value of the electronicPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public void setElectronicPlaceInfo(ElectronicPlaceInfoType value) {
        this.electronicPlaceInfo = value;
    }

    /**
     * Gets the value of the placingProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseNoticeDataType.PlacingProcedure }
     *     
     */
    public PurchaseNoticeDataType.PlacingProcedure getPlacingProcedure() {
        return placingProcedure;
    }

    /**
     * Sets the value of the placingProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseNoticeDataType.PlacingProcedure }
     *     
     */
    public void setPlacingProcedure(PurchaseNoticeDataType.PlacingProcedure value) {
        this.placingProcedure = value;
    }

    /**
     * Gets the value of the submissionCloseDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionCloseDateTime() {
        return submissionCloseDateTime;
    }

    /**
     * Sets the value of the submissionCloseDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionCloseDateTime(XMLGregorianCalendar value) {
        this.submissionCloseDateTime = value;
    }

    /**
     * Gets the value of the publicationPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationPlannedDate() {
        return publicationPlannedDate;
    }

    /**
     * Sets the value of the publicationPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationPlannedDate(XMLGregorianCalendar value) {
        this.publicationPlannedDate = value;
    }

    /**
     * Gets the value of the templateVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTemplateVersion() {
        return templateVersion;
    }

    /**
     * Sets the value of the templateVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTemplateVersion(Long value) {
        this.templateVersion = value;
    }

    /**
     * Gets the value of the extendFields property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeTemplateFieldValueListType }
     *     
     */
    public NoticeTemplateFieldValueListType getExtendFields() {
        return extendFields;
    }

    /**
     * Sets the value of the extendFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeTemplateFieldValueListType }
     *     
     */
    public void setExtendFields(NoticeTemplateFieldValueListType value) {
        this.extendFields = value;
    }

    /**
     * Gets the value of the lots property.
     * 
     * @return
     *     possible object is
     *     {@link LotISListType }
     *     
     */
    public LotISListType getLots() {
        return lots;
    }

    /**
     * Sets the value of the lots property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotISListType }
     *     
     */
    public void setLots(LotISListType value) {
        this.lots = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="examinationPlace">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="2000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="examinationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="summingupDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="summingupPlace" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="2000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "examinationPlace",
        "examinationDateTime",
        "summingupDateTime",
        "summingupPlace"
    })
    public static class PlacingProcedure {

        @XmlElement(required = true)
        protected String examinationPlace;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar examinationDateTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar summingupDateTime;
        protected String summingupPlace;

        /**
         * Gets the value of the examinationPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExaminationPlace() {
            return examinationPlace;
        }

        /**
         * Sets the value of the examinationPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExaminationPlace(String value) {
            this.examinationPlace = value;
        }

        /**
         * Gets the value of the examinationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getExaminationDateTime() {
            return examinationDateTime;
        }

        /**
         * Sets the value of the examinationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setExaminationDateTime(XMLGregorianCalendar value) {
            this.examinationDateTime = value;
        }

        /**
         * Gets the value of the summingupDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSummingupDateTime() {
            return summingupDateTime;
        }

        /**
         * Sets the value of the summingupDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setSummingupDateTime(XMLGregorianCalendar value) {
            this.summingupDateTime = value;
        }

        /**
         * Gets the value of the summingupPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSummingupPlace() {
            return summingupPlace;
        }

        /**
         * Sets the value of the summingupPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSummingupPlace(String value) {
            this.summingupPlace = value;
        }

    }

}
