//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:17:31 PM MSK 
//


package ru.gov.zakupki._223fz.dishonestsupplier._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki._223fz.dishonestsupplier._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki._223fz.dishonestsupplier._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DishonestApplicationReject }
     * 
     */
    public DishonestApplicationReject createDishonestApplicationReject() {
        return new DishonestApplicationReject();
    }

    /**
     * Create an instance of {@link DishonestSupplierExcludeType }
     * 
     */
    public DishonestSupplierExcludeType createDishonestSupplierExcludeType() {
        return new DishonestSupplierExcludeType();
    }

    /**
     * Create an instance of {@link DishonestSupplierReject }
     * 
     */
    public DishonestSupplierReject createDishonestSupplierReject() {
        return new DishonestSupplierReject();
    }

    /**
     * Create an instance of {@link DishonestApplicationInfoType }
     * 
     */
    public DishonestApplicationInfoType createDishonestApplicationInfoType() {
        return new DishonestApplicationInfoType();
    }

    /**
     * Create an instance of {@link DishonestApplicationRejectType }
     * 
     */
    public DishonestApplicationRejectType createDishonestApplicationRejectType() {
        return new DishonestApplicationRejectType();
    }

    /**
     * Create an instance of {@link DishonestSupplierInfoType }
     * 
     */
    public DishonestSupplierInfoType createDishonestSupplierInfoType() {
        return new DishonestSupplierInfoType();
    }

    /**
     * Create an instance of {@link DishonestSupplierIncludeType }
     * 
     */
    public DishonestSupplierIncludeType createDishonestSupplierIncludeType() {
        return new DishonestSupplierIncludeType();
    }

    /**
     * Create an instance of {@link DishonestApplicationReject.Body }
     * 
     */
    public DishonestApplicationReject.Body createDishonestApplicationRejectBody() {
        return new DishonestApplicationReject.Body();
    }

    /**
     * Create an instance of {@link DishonestSupplierExcludeType.Body }
     * 
     */
    public DishonestSupplierExcludeType.Body createDishonestSupplierExcludeTypeBody() {
        return new DishonestSupplierExcludeType.Body();
    }

    /**
     * Create an instance of {@link DishonestSupplierReject.Body }
     * 
     */
    public DishonestSupplierReject.Body createDishonestSupplierRejectBody() {
        return new DishonestSupplierReject.Body();
    }

    /**
     * Create an instance of {@link DishonestApplicationInfoType.Body }
     * 
     */
    public DishonestApplicationInfoType.Body createDishonestApplicationInfoTypeBody() {
        return new DishonestApplicationInfoType.Body();
    }

    /**
     * Create an instance of {@link DishonestApplicationRejectType.Body }
     * 
     */
    public DishonestApplicationRejectType.Body createDishonestApplicationRejectTypeBody() {
        return new DishonestApplicationRejectType.Body();
    }

    /**
     * Create an instance of {@link DishonestSupplierInfoType.Body }
     * 
     */
    public DishonestSupplierInfoType.Body createDishonestSupplierInfoTypeBody() {
        return new DishonestSupplierInfoType.Body();
    }

    /**
     * Create an instance of {@link DishonestSupplierIncludeType.Body }
     * 
     */
    public DishonestSupplierIncludeType.Body createDishonestSupplierIncludeTypeBody() {
        return new DishonestSupplierIncludeType.Body();
    }

    /**
     * Create an instance of {@link DishonestApplicationType }
     * 
     */
    public DishonestApplicationType createDishonestApplicationType() {
        return new DishonestApplicationType();
    }

    /**
     * Create an instance of {@link DishonestSupplierRejectItemType }
     * 
     */
    public DishonestSupplierRejectItemType createDishonestSupplierRejectItemType() {
        return new DishonestSupplierRejectItemType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link DishonestApplicationRejectItemType }
     * 
     */
    public DishonestApplicationRejectItemType createDishonestApplicationRejectItemType() {
        return new DishonestApplicationRejectItemType();
    }

    /**
     * Create an instance of {@link DishonestSupplierExcludeItemType }
     * 
     */
    public DishonestSupplierExcludeItemType createDishonestSupplierExcludeItemType() {
        return new DishonestSupplierExcludeItemType();
    }

    /**
     * Create an instance of {@link DishonestApplicationInfoDataType }
     * 
     */
    public DishonestApplicationInfoDataType createDishonestApplicationInfoDataType() {
        return new DishonestApplicationInfoDataType();
    }

    /**
     * Create an instance of {@link DishonestSupplierType }
     * 
     */
    public DishonestSupplierType createDishonestSupplierType() {
        return new DishonestSupplierType();
    }

    /**
     * Create an instance of {@link IncludeReasonType }
     * 
     */
    public IncludeReasonType createIncludeReasonType() {
        return new IncludeReasonType();
    }

    /**
     * Create an instance of {@link DishonestSupplierInfoItemType }
     * 
     */
    public DishonestSupplierInfoItemType createDishonestSupplierInfoItemType() {
        return new DishonestSupplierInfoItemType();
    }

    /**
     * Create an instance of {@link DishonestSupplierIncludeItemType }
     * 
     */
    public DishonestSupplierIncludeItemType createDishonestSupplierIncludeItemType() {
        return new DishonestSupplierIncludeItemType();
    }

    /**
     * Create an instance of {@link PurchaseInfoDataType }
     * 
     */
    public PurchaseInfoDataType createPurchaseInfoDataType() {
        return new PurchaseInfoDataType();
    }

    /**
     * Create an instance of {@link AgencyAddressType }
     * 
     */
    public AgencyAddressType createAgencyAddressType() {
        return new AgencyAddressType();
    }

    /**
     * Create an instance of {@link DishonestSupplierExcludeDataType }
     * 
     */
    public DishonestSupplierExcludeDataType createDishonestSupplierExcludeDataType() {
        return new DishonestSupplierExcludeDataType();
    }

    /**
     * Create an instance of {@link DishonestApplicationRejectDataType }
     * 
     */
    public DishonestApplicationRejectDataType createDishonestApplicationRejectDataType() {
        return new DishonestApplicationRejectDataType();
    }

    /**
     * Create an instance of {@link DishonestApplicationInfoItemType }
     * 
     */
    public DishonestApplicationInfoItemType createDishonestApplicationInfoItemType() {
        return new DishonestApplicationInfoItemType();
    }

    /**
     * Create an instance of {@link DocumentRequisitesType }
     * 
     */
    public DocumentRequisitesType createDocumentRequisitesType() {
        return new DocumentRequisitesType();
    }

    /**
     * Create an instance of {@link DishonestSupplierInfoDataType }
     * 
     */
    public DishonestSupplierInfoDataType createDishonestSupplierInfoDataType() {
        return new DishonestSupplierInfoDataType();
    }

    /**
     * Create an instance of {@link SupplierDataType }
     * 
     */
    public SupplierDataType createSupplierDataType() {
        return new SupplierDataType();
    }

    /**
     * Create an instance of {@link DishonestSupplierRejectDataType }
     * 
     */
    public DishonestSupplierRejectDataType createDishonestSupplierRejectDataType() {
        return new DishonestSupplierRejectDataType();
    }

    /**
     * Create an instance of {@link DishonestSupplierIncludeDataType }
     * 
     */
    public DishonestSupplierIncludeDataType createDishonestSupplierIncludeDataType() {
        return new DishonestSupplierIncludeDataType();
    }

    /**
     * Create an instance of {@link ContractInformationType }
     * 
     */
    public ContractInformationType createContractInformationType() {
        return new ContractInformationType();
    }

    /**
     * Create an instance of {@link ApplicationPositionType }
     * 
     */
    public ApplicationPositionType createApplicationPositionType() {
        return new ApplicationPositionType();
    }

    /**
     * Create an instance of {@link AgencyType }
     * 
     */
    public AgencyType createAgencyType() {
        return new AgencyType();
    }

}
