//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.23 at 05:29:48 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zakupki.gov.ru/223fz/orderClauseList/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gov.zakupki._223fz.orderclauselist._1;
